### ISSUE TITLE
Consider using an existing image format over a custom one

### ISSUE THREAD

**Issue by Th3Fanbus** [universalpayload/documentation#10]
Instead of defining a completely new image header for payloads, I would much prefer to use an already-existing format, such as ELF (Executable and Linkable Format). Using mature, widely-used formats is simpler and eliminates the problems that may arise when defining a new image format, such as endianness. Given that TianoCore can already be built as an ELF executable, it shouldn't be too hard to switch payload build systems to generate ELF objects.

[![](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

**Comment by mauricema** [comment]
Very good feedback.  And this is also what we concerned about in our initial discussion.  As a result, we decided to capture all the open options in the draft spec, and then hear back from the community on the prefered option.  We think it can guide us to the right direction.  Your point is taken, and we will look into the option to see if we can converge onto an already-existing format instead of defining a new format.  Thank you !

BTW, just want to clarify on your statement "TianoCore can already be built as an ELF executable".  Could you help provide some reference on that?   As far as I know, TianoCore is following FV format and each FFS is PE/COFF format as required by the UEFI PI spec. If it is built in GCC, the ELF format will be repackaged back into PE format by EDKII build.  So I want to see the actual example on how the TianoCore was built into an ELF if you have seen one.

**Comment by Th3Fanbus** [comment]
Hi Maurice,

> BTW, just want to clarify on your statement "TianoCore can already be built as an ELF executable". Could you help provide some reference on that? As far as I know, TianoCore is following FV format and each FFS is PE/COFF format as required by the UEFI PI spec. If it is built in GCC, the ELF format will be repackaged back into PE format by EDKII build. So I want to see the actual example on how the TianoCore was built into an ELF if you have seen one.

Sorry for the confusion. I thought this was done when building TianoCore as a coreboot payload, but instead the TianoCore FV is packaged into a SELF (Simple ELF) when adding it into the CBFS (coreboot filesystem). SELF is coreboot's very simple take on the standard ELF format, and is described here: https://www.coreboot.org/SELF

**Comment by mauricema** [comment]
Got it.  Thank you for the additional clarification.  So that is not the standard ELF format.

**Comment by gdong1** [comment]
Let's continue collect the feedback on the image format.
Now we are trending to use existing ELF image format as universal payload format. If there is no more feedback on it in the next few weeks, we could update the specification to reflect this change.

**Comment by marksdoran** [comment]
Is the question of image format decided now??  I completely agree that making up a new one (especially if that just wraps all the existing ones of interest) seems close to an Obviously Bad Idea(tm).  ELF seems to have more or less won in terms of widespread use.  EDK2 elements can be built with tools that support ELF already.  If the UEFI PI Spec is the only reason holding this back...let me know...that's something we can try and address.

**Comment by gdong1** [comment]
Yes. It looks like ELF format is the favorite format from community feedback. We may have to do some investigation to check if PI spec changes needed, if yes, will reach out to you.

**Comment by gdong1** [comment]
It was addressed in version 0.75 to use ELF image format.
